<?php

namespace App\Http\Requests\Api\User;

use App\Http\Requests\BaseRequest;

class LoginRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'phone'=>'required|numeric',
            'password'=>'required|min:6',
//            'token'=>'required',
        ];
    }
    public function messages()
    {
        return [
            'phone.required'=>__('validation.phone'),
            'password.required'=>__('validation.password'),
            'password.min'=>__('validation.min_password'),
//            'token.required'=>__('validation.token'),
        ]; // TODO: Change the autogenerated stub
    }
}
