<?php

namespace App\Http\Requests\Admin\City;

use App\Http\Requests\BaseRequest;

class AddCityRequest extends BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name_ar'=>'required',
            'name_en'=>'required',
        ];
    }
    public function messages()
    {
        return [
            'name_ar.required'=>__('validation.name_ar'),
            'name_en.required'=>__('validation.name_en'),
        ]; // TODO: Change the autogenerated stub
    }
}
